Inua/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('sms/', include('sms.urls')),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.category_home, name='categories'),
    path('category/<int:pk>', views.prod_list, name='prod_list'),
    path('product/<int:pk>', views.prod_detail, name='prod_detail'),
    path('sales', views.sale_form, name='sales'),
    path('all-sales', views.sales_home, name='all_sales'),
    path('ajax/load-products', views.load_products, name='ajax_load_products'),
]

sms/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.sms_home, name='sms_home'),
]

products/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=500, null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now, null=False, blank=False)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='p_category', null=False, blank=False, on_delete=models.CASCADE)
    name = models.CharField(max_length=1000, blank=False, null=False)
    total_quantity = models.CharField(max_length=1000, blank=False, null=False)
    current_quantity = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now, null=False, blank=False)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Quantity(models.Model):
    product = models.ForeignKey(Product, related_name='p_quantity', null=False, blank=False, on_delete=models.CASCADE)
    name = models.CharField(max_length=10, null=True, blank=True)
    quantity = models.PositiveIntegerField(null=True, blank=True)
    price = models.CharField(max_length=1000, null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now, null=False, blank=False)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name + " " + self.quantity


class Sale(models.Model):
    category = models.ForeignKey(Category, related_name="sale_category", null=True, blank=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, related_name="sale_product", null=False, blank=False, on_delete=models.CASCADE)
    quantity = models.CharField(max_length=1000, blank=False, null=False)
    amount = models.CharField(max_length=1000, blank=False, null=False)
    created_at = models.DateTimeField(default=timezone.now, null=True, blank=True)

    def __str__(self):
        return self.product.name

products/forms.py
from django import forms
from .models import Category, Product, Sale, Quantity


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        exclude = ('created_at',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'au-input au-input--full', 'required': 'true'}),
        }


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('category', 'created_at',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'au-input au-input--full', 'required': 'true'}),
            'total_quantity': forms.TextInput(attrs={'class': 'au-input au-input--full', 'required': 'true'}),
        }


class QuantityForm(forms.ModelForm):
    class Meta:
        model = Quantity
        exclude = ('product', 'created_at')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'au-input au-input--full', 'required': 'true'}),
            'quantity': forms.TextInput(attrs={'class': 'au-input au-input--full', 'required': 'true'}),
            'price': forms.TextInput(attrs={'class': 'au-input au-input--full', 'required': 'true'}),
        }


class SaleForm(forms.ModelForm):

    class Meta:
        model = Sale
        fields = ('category', 'product', 'quantity', 'amount',)
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control'}),
            'product': forms.Select(attrs={'class': 'form-control'}),
            'quantity': forms.TextInput(attrs={'class': 'au-input au-input--full', 'required': 'true'}),
            'amount': forms.TextInput(attrs={'class': 'au-input au-input--full', 'required': 'true'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['product'].queryset = Product.objects.none()

        if 'category' in self.data:
            try:
                category_id = int(self.data.get('category'))
                self.fields['product'].queryset = Product.objects.filter(category_id=category_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['product'].queryset = self.instance.country.city_set.order_by('name')

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category, Product, Sale, Quantity
from .forms import CategoryForm, ProductForm, SaleForm, QuantityForm
from django.contrib import messages


def category_home(request):
    template_name = 'products/category.html'
    categories = Category.objects.all()
    if request.method == 'POST':
        form = CategoryForm(request.POST or None)
        if form.is_valid():
            cat = form.save(commit=False)
            cat.save()

            return redirect('categories')

    else:
        form = CategoryForm()

    data = {
        'categories': categories,
        'form': form
    }

    return render(request, template_name, data)


def prod_list(request, pk):
    template_name = "products/products.html"
    category = Category.objects.get(pk=pk)
    products = Product.objects.filter(category=category)
    if request.method == 'POST':
        form = ProductForm(request.POST or None)
        if form.is_valid():
            t_q = form.cleaned_data.get('total_quantity')
            product = form.save(commit=False)
            product.category = category
            product.current_quantity = t_q
            product.save()

            return redirect()
    else:
        form = ProductForm()

    data = {
        'form': form,
        'products': products,
    }

    return render(request, template_name, data)


def prod_detail(request, pk):
    template_name = "products/product.html"
    prod = get_object_or_404(Product, pk=pk)
    quants = Quantity.objects.filter(product=prod)
    if request.method == 'POST':
        form = QuantityForm(request.POST or None)
        if form.is_valid():
            quantity = form.save(commit=False)
            quantity.product = prod
            quantity.save()

            return redirect('prod_detail', pk=pk)
    else:
        form = QuantityForm()

    data = {
        'form': form,
        'quants': quants,
        'prod': prod
    }

    return render(request, template_name, data)


def sale_form(request):
    template_name = "products/sales.html"
    if request.method == 'POST':
        form = SaleForm(request.POST or None)
        if form.is_valid():
            quantity = form.cleaned_data.get('quantity')
            sale_product = form.cleaned_data.get('product')
            prod = Product.objects.get(name=sale_product)
            c_q = prod.current_quantity
            n_q = float(c_q) - float(quantity)
            sale = form.save(commit=False)
            prod.current_quantity = n_q
            prod.save()
            sale.save()
            messages.info(request, "Transaction successful. Thank You.")
            return redirect('sales')
    else:
        form = SaleForm()
    data = {
        'form': form,
    }

    return render(request, template_name, data)


def sales_home(request):
    template_name = "products/all_sales.html"
    sales = Sale.objects.all().order_by("-created_at")

    data = {
        'sales': sales,
    }

    return render(request, template_name, data)


def load_products(request):
    category_id = request.GET.get('category')
    products = Product.objects.filter(category__id=category_id)
    return render(request, 'products/products_list.html', {'products': products})

templates/products/all_sales.html
{% extends 'base.html' %}
{% load static  %}

{% block content %}
<div class="row m-t-30">
    <div class="col-md-12">
        <!-- DATA TABLE-->
        <div class="table-responsive m-b-40">
            <table class="table table-borderless table-data3">
                <thead>
                    <tr>
                        <th>Product Name</th>
                        <th>Quantity</th>
                        <th>Cost</th>
                        <th>Date Created</th>
                    </tr>
                </thead>
                <tbody>
                	{% for sale in sales %}
                    <tr>
                        <td>{{sale.product.name}}</td>
                        <td>{{sale.quantity}} Kg</td>
                        <td>{{sale.amount}} Ksh</td>
                        <td>{{sale.created_at|date:"d-m-Y H:m"}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- END DATA TABLE-->
    </div>
</div>
{% endblock %}

templates/products/category.html
{% extends 'base.html' %}

{% block content %}
<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        Add Category
</button>
</p>
<div class="collapse" id="collapseExample">
	<div class="card">
        <div class="card-header">
            <strong>Category</strong> Form
        </div>
        <div class="card-body card-block">
            <form action="" method="post" class="">
            	{% csrf_token %}
                <div class="form-group">
                    <label for="nf-email" class=" form-control-label">Enter Category Name:</label>
                    {{form.name}}
                </div>
                <div class="card-footer">
		            <button type="submit" class="btn btn-primary btn-md">
		                <i class="fa fa-dot-circle-o"></i> Submit
		            </button>
		        </div>
            </form>
        </div>
    </div>
</div>
<br>
<div class="row">
	{% for cat in categories %}
	<div class="col-md-4">
		<a href="{% url 'prod_list' pk=cat.pk %}" style="display: block; position: relative; color: black;">
	        <div class="card">
	            <div class="card-header">
	                <strong class="card-title">Category</strong>
	            </div>
	            <div class="card-body">
	               <center><strong>{{cat.name}}</strong></center>
	            </div>
	        </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/products/product.html
{% extends 'base.html' %}

{% block content %}
<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        Add Product Quantity
</button>
</p>
<div class="collapse" id="collapseExample">
    <div class="card">
        <div class="card-header">
            <strong>Quantity</strong> Form
        </div>
        <div class="card-body card-block">
            <form action="" method="post" class="">
                {% csrf_token %}
                <div class="form-group">
                    <label for="nf-email" class=" form-control-label">Enter Quantity Name:</label>
                    {{form.name}}
                </div>
                <div class="form-group">
                    <label for="nf-email" class=" form-control-label">Enter Quantity Amount:</label>
                    {{form.quantity}}
                </div>
                <div class="form-group">
                    <label for="nf-email" class=" form-control-label">Enter Price:</label>
                    {{form.price}}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-md">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<br>
<div class="row m-t-30">
    <div class="col-md-12">
        <!-- DATA TABLE-->
        <div class="table-responsive m-b-40">
            <table class="table table-borderless table-data3">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Amount</th>
                        <th>Price</th>
                        <th>Last Update</th>
                    </tr>
                </thead>
                <tbody>
                	{% for q in quants %}
                    <tr>
                        <td>{{q.name}}</td>
                        <td>{{q.quantity}}</td>
                        <td>Ksh. {{q.price}}</td>
                        <td>{{q.updated_at}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- END DATA TABLE-->
    </div>
</div>
{% endblock %}

templates/products/products.html
{% extends 'base.html' %}

{% block content %}
<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        Add Product
</button>
</p>
<div class="collapse" id="collapseExample">
    <div class="card">
        <div class="card-header">
            <strong>Product</strong> Form
        </div>
        <div class="card-body card-block">
            <form action="" method="post" class="">
                {% csrf_token %}
                <div class="form-group">
                    <label for="nf-email" class=" form-control-label">Enter Product Name:</label>
                    {{form.name}}
                </div>
                <div class="form-group">
                    <label for="nf-email" class=" form-control-label">Enter Product Quantity:</label>
                    {{form.total_quantity}}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-md">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<br>
<div class="row m-t-30">
    <div class="col-md-12">
        <!-- DATA TABLE-->
        <div class="table-responsive m-b-40">
            <table class="table table-borderless table-data3">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Start Quantity</th>
                        <th>Current Quantity</th>
                        <th>Last Updated</th>
                    </tr>
                </thead>
                <tbody>
                	{% for prod in products %}
                    
                    <tr>
                        <td><a href="{% url 'prod_detail' pk=prod.pk %}" style="display: block; position: relative; color: black;">{{prod.name}}</a></td>
                        <td>{{prod.total_quantity}} </td>
                        <td>{{prod.current_quantity}} </td>
                        <td>{{prod.updated_at}}</td>
                        
                    </tr>
                    
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- END DATA TABLE-->
    </div>
</div>
{% endblock %}

templates/products/products_list.html
<option value="">---------</option>
{% for prod in products %}
<option value="{{ prod.pk }}">{{ prod.name }}</option>
{% endfor %}

templates/products/sales.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<a class="btn btn-primary" href="{% url 'all_sales' %}" style="float: right;">
        View All Sales
</a>
<br>
<div class="row">
    <div class="col-md-12">
        <div class="overview-wrap">
            <h2 class="title-1">Sales</h2>
        </div>
    </div>
</div>
{% if messages %}
  {% for m in messages %}
    <div class="sufee-alert alert with-close alert-success alert-dismissible fade show">
      <span class="badge badge-pill badge-success">Success</span>
          {{m}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">×</span>
      </button>
  </div>
  {% endfor %}
{% endif %}
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
        <span class="badge badge-pill badge-danger">Warning</span>
        <strong>{{field.name}} :{{ error|escape }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
    {% endfor %}
  {% endfor %}
{% endif %}

<div class="login-wrap">
    <div class="login-content">
        <div class="login-logo">
            <a href="#">
                <img src="{% static 'images/icon/ki_logo.jpeg' %}" alt="Karimi Integrated" >
            </a>
        </div>
        <div class="login-form">
            <form method="post" id="saleForm" data-products-url="{% url 'ajax_load_products' %}" novalidate>
            	{% csrf_token %}
              <div class="form-group">
                    <label>Category</label>
                    {{form.category}}
                </div>
                <div class="form-group">
                    <label>Product</label>
                    {{form.product}}
                </div>
                <div class="form-group">
                    <label>Quantity</label>
                    {{form.quantity}}
                </div>
                <div class="form-group">
                    <label>Amount</label>
                    {{form.amount}}
                </div>
                <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit">submit</button>
                {% if form.errors%}
					{% for field in form %}
				        {% for error in field.errors %}
				            <div class="alert alert-danger">
				                <strong>{{field.name}} :{{ error|escape }}</strong>
				            </div>
				        {% endfor %}
				    {% endfor %}
                      {% for error in form.errors %}
                        <ul>
                            <li>Error: {{error|escape}} is already taken or is invalid </li>
                        </ul>
                      {% endfor %}
                      {% for error in form.non_field_errors %}
                          <ul>
                              <li>Errorr: {{error|escape}}</li>
                          </ul>
                      {% endfor %}
                      {% for error in form.non_form_errors %}
                          <ul>
                              <li>Errorr: {{error|escape}}</li>
                          </ul>
                      {% endfor %}
                {% endif %}
            </form>
            
        </div>
    </div>
</div>

{% endblock %}
{% block script %}
<script type="text/javascript">
   $("#id_category").change(function () {
      var url = $("#saleForm").attr("data-products-url");
      var categoryId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'category': categoryId
        },
        success: function (data) {
          $("#id_product").html(data);
        }
      });

    });
</script>
{% endblock %}